spring:
  application:
    name: graphql-books

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  graphql:
    graphiql:
      enabled: true
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
    health:
      show-details: always
  
  tracing:
    sampling: 
      probability: 1.0     
      
#  threads:
#    virtual:
#      enabled: true